#!/usr/bin/env bash
# Install nginx on the web-01 server
old_url="\tserver_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent;"

sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'

echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "s/server_name _;/$old_url/" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
replace2="\n\terror_page 404 /custom_404.html;\n\tlocation = /var/www/html/custom_404.html {\n\t\tinternal;\n\t}"

sudo sed -i "47i\ $replace2" /etc/nginx/sites-available/default

sudo service nginx restart
