#!/usr/bin/env bash
#configure HAproxy on your lb-01 server.

sudo apt -y update
sudo apt -y upgrade

sudo apt-get install -y --no-install-recommends software-properties-common
sudo apt-get install -y haproxy


echo "
frontend http
        bind *:80
        mode http
        default_backend web-backend

backend web-backend
        balance roundrobin
        mode http
        server 4298-web-01 3.80.49.204:80 check
        server 4298-web-02 34.229.127.31:80 check

" | sudo tee /etc/haproxy/haproxy.cfg

# Restar HAproxy Server
sudo service haproxy restart
