#!/usr/bin/env bash
# This script that displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed


FILE=school
if [ -f "$FILE" ] || [ -d "$FILE" ]
then  
	echo "$FILE file exists"
	if [ -s $FILE ]
	then
		echo "$FILE file is not empty"
	else
		echo "$FILE file is empty"
	fi
	if [ -f $FILE ]
	then
		echo "$FILE is a regular file"
	fi
else
	echo "$FILE file does not exist"
fi
