#!/usr/bin/env bash
# Requirements:
# write a Bash script that accepts one argument
# the script should run the whoami command under the user passed as an argument


sudo -u "$1" whoami
#-u :Run the command as a user other than the default target user (usually root). 
#-s :Run the shell specified by the SHELL environment variable if it is set or the shell specified. 
